import { CondicionOfertaCrud } from './condicion.oferta.crud';
import { CondicionEntfedCrud } from './condicion.entfed.crud';
import { EstadoEfCrud } from './estado.ef.crud';
import { MotivoSuspensionCrud } from './motivo.suspension.crud';
import { Documento } from 'src/app/common/domain/documento';
import { RegistroPatronal } from './registro-patronal';
import { PrestadorServiciosEF } from './prestador.servicios.ef';
import { DocumentoEFPS } from './documento.ef.ps';
import { BitacoraEstatusEF } from './bitacora.estatus.ef';

export class EntidadFinancieraCrud {
  id?: number;
  rfc?: string;
  razonSocial?: string;
  nombreComercial?: string;
  numeroTelefono?: string;
  telefonoAtencionClientes?: string;
  paginaWeb?: string;
  correoElectronico?: string;
  catPromedio?: string;
  idDelegacion?: string;
  idSubdelegacion?: string;
  registroPatronal?: string;
  mclcCondicionEntfedCollection?: CondicionEntfedCrud[];
  mclcCondicionOfertaCollection?: CondicionOfertaCrud[];
  mclcEstadoEf?: EstadoEfCrud;
  mclcMotivoSuspension?: MotivoSuspensionCrud;
  curpRepresentanteLegal?: any;
  nombreLegal?: any;
  primerApeLegal?: any;
  segundoApeLegal?: any;
  correo2?: any;
  correo3?: any;
  direccion?: any;
  fecFirmaContra?: string;
  fecFirmaContraDate?: Date;
  fecIniFirmaContra?: string;
  fecIniFirmaContraDate?: Date;
  numeroProveedor?: any;
  instBancaria?: any;
  descBanco?: any;
  clabe?: any;
  confClabe?: any;
  curpAdmin?: any;
  nombreAdmin?: any;
  primerApAdmin?: any;
  segundoApeAdmin?: any;
  correoAdmin?: any;
  adminRFC?:string;
  enableModificar?: boolean;
  valueCorreModAdmin?: string;
  valueCurpModAdmin?: string;
  valueRfcModAdmin?: string;
  logo?: Documento;
  idInstFinanciera?:any;
  sinConvenio?:any;
  mcltRegistrosPatronalesCollection?: RegistroPatronal[];
  prestadorServicioCertificado?: PrestadorServiciosEF;
  prestadorServicioValidacionBiometrica?: PrestadorServiciosEF;
  documentosPSCertificado?: DocumentoEFPS[]; 
  documentosPSValidacionBiometrica?: DocumentoEFPS[];
  existeDocPSCertificado?: boolean;
  existeDocPSValidacionBiometrica?: boolean;
  bitacoraEstatusEF?: BitacoraEstatusEF;
  mostrarComponentesEdicionPSCertificacion?: boolean;
  mostrarComponentesEdicionPSValidacionBiometrica?: boolean;
  prestadorServicioCertificadoAnt?: PrestadorServiciosEF;
  prestadorServicioValidacionBiometricaAnt?: PrestadorServiciosEF;
}
